name: CI - validação de PRs

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Build
        run: npm run build

      - name: Testes
        run: npm test

      - name: Validar commits semânticos
        run: npx commitlint --from=HEAD~1
